model:
  base_learning_rate: 5.0e-07
  target: ldm_seg.models.ldznet.ldznet_model.LatentSeg
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 48
    channels: 1
    cond_stage_trainable: true   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    # ignore_keys: [ "transformer_blocks" ]
    # model_lr: 1.0e-6
    # unfreeze_model: True
    # use_ema: False

    # personalization_config:
    #   target: ldm_seg.modules.embedding_manager.EmbeddingManager
    #   params:
    #     placeholder_strings: ["*"]
    #     initializer_words: ["ophanim"] # ["sculpture"]
    #     per_image_tokens: false
    #     num_vectors_per_token: 1
    #     progressive_words: False

    # scheduler_config: # 10000 warmup steps
    #   target: ldm_seg.lr_scheduler.LambdaLinearScheduler
    #   params:
    #     warm_up_steps: [ 10000 ]
    #     cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
    #     f_start: [ 1.e-6 ]
    #     f_max: [ 1. ]
    #     f_min: [ 1. ]

    unet_config:
      target: ldm_seg.modules.diffusionmodules.ldznet_UNet.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 1
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True # Not sure to keep this or not
        legacy: False # Not sure to keep this or not

    first_stage_config:
      target: ldm_seg.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 384
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm_seg.modules.encoders.modules.FrozenCLIPEmbedder
    
    sd_features_stage_config:
      target: ldm_seg.modules.encoders.modules.FrozenSDUNet
      params:
        path: ../checkpoints/Stable-diffusion-v1/sd-v1-4-full-ema.ckpt
        config: ../configs/stable-diffusion/v1-inference.yaml
        timesteps: [ 300, 400, 500 ]

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 16
    wrap: false
    train:
      target: ldm_seg.data.phrasecut.PhraseCut
      params:
        split: train
        mask: text
        image_size: 384
    validation:
      target: ldm_seg.data.phrasecut.PhraseCut
      params:
        split: val
        mask: text
        image_size: 384
        # batch_size: 32
        # repeats: 10

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 500
  # callbacks:
  #   image_logger:
  #     target: main.ImageLogger
  #     params:
  #       batch_frequency: 500
  #       max_images: 2
  #       increase_log_steps: False

  trainer:
    benchmark: True
    max_steps: 2560000
    find_unused_parameters: False